// p2tl-kinerja.js v1.0 — Kinerja P2TL
// Integrated into Transaksi Energi > Pengendalian Susut
// Data source: KINERJA TE 2026.xlsx — Sheet REAL SEM I
(function(){
"use strict";
var BULANAN={jan:{target:1448724,realisasi:1356326,pct:93.62,ulp:[{kode:"53401",nama:"Jatibarang",target:321938,realisasi:299924,pct:93.16},{kode:"53402",nama:"Haurgeulis",target:321938,realisasi:299855,pct:93.14},{kode:"53403",nama:"Indramayu Kota",target:402424,realisasi:374642,pct:93.10},{kode:"53404",nama:"Cikedung",target:402424,realisasi:381905,pct:94.90}]},feb:{target:1303852,realisasi:1311873,pct:100.62,ulp:[{kode:"53401",nama:"Jatibarang",target:289745,realisasi:290299,pct:100.19},{kode:"53402",nama:"Haurgeulis",target:289745,realisasi:291541,pct:100.62},{kode:"53403",nama:"Indramayu Kota",target:362181,realisasi:365124,pct:100.81},{kode:"53404",nama:"Cikedung",target:362181,realisasi:364909,pct:100.75}]}};
var KUMULATIF={target:2752576,realisasi:2668199,pct:96.93,gap:-84377,ulp:[{kode:"53401",nama:"Jatibarang",target:611683,realisasi:590223,pct:96.49,gap:-21460},{kode:"53402",nama:"Haurgeulis",target:611683,realisasi:591396,pct:96.68,gap:-20287},{kode:"53403",nama:"Indramayu Kota",target:764605,realisasi:739766,pct:96.75,gap:-24839},{kode:"53404",nama:"Cikedung",target:764605,realisasi:746814,pct:97.67,gap:-17791}]};
var TARGET_TAHUN={total:16225752};
var BULAN_LABELS=["Jan","Feb"];var BULAN_DATA=[BULANAN.jan,BULANAN.feb];
function fmt(n){if(n==null||isNaN(n))return"-";return Number(n).toLocaleString("id-ID");}
function fmtPct(n){if(n==null||isNaN(n))return"-";return n.toFixed(2).replace(".",",")+"%";}
function getSC(p){if(p>=100)return{bg:"rgba(16,185,129,.15)",bd:"#10b981",tx:"#34d399",lb:"TERCAPAI"};if(p>=90)return{bg:"rgba(59,130,246,.15)",bd:"#3b82f6",tx:"#60a5fa",lb:"BAIK"};if(p>=75)return{bg:"rgba(245,158,11,.15)",bd:"#f59e0b",tx:"#fbbf24",lb:"PERHATIAN"};return{bg:"rgba(239,68,68,.15)",bd:"#ef4444",tx:"#f87171",lb:"KRITIS"};}
function badge(p){var s=getSC(p);return '<span style="background:'+s.bg+';color:'+s.tx+';padding:2px 8px;border-radius:6px;font-size:.7em;font-weight:600;border:1px solid '+s.bd+'">'+s.lb+'</span>';}
function renderP2TL(){
var ct=document.getElementById("ct");if(!ct)return;
var rk=null;for(var i=0;i<ct.children.length;i++){if(ct.children[i].textContent&&ct.children[i].textContent.indexOf("Rekomendasi Pengendalian Susut")!==-1){rk=ct.children[i];break;}}
var ok=false;for(var j=0;j<ct.children.length;j++){if((ct.children[j].textContent||"").indexOf("Pengendalian Susut Distribusi")!==-1){ok=true;break;}}
if(!ok)return;
var ex=document.getElementById("p2tl-kinerja-section");if(ex)ex.remove();
var sec=document.createElement("div");sec.id="p2tl-kinerja-section";
var prog=(KUMULATIF.realisasi/TARGET_TAHUN.total*100);
var sk=getSC(KUMULATIF.pct);var gc=KUMULATIF.gap>=0?"#34d399":"#f87171";
var h='<div style="background:linear-gradient(135deg,#0f1b35,#1a2d5e,#0f1b35);border:1px solid #1e3054;border-radius:12px;padding:24px;margin-bottom:16px;text-align:center;position:relative;overflow:hidden"><div style="position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#8b5cf6,#3b82f6,#06b6d4,#10b981)"></div><h3 style="color:#f8fafc;font-size:1.3em;margin:0 0 8px;letter-spacing:1px">\u26A1 KINERJA P2TL (Penertiban Pemakaian Tenaga Listrik)</h3><div style="color:#94a3b8;font-size:.85em">Realisasi kWh P2TL per ULP \u2014 UP3 Indramayu \u2014 Tahun 2026</div></div>';
h+='<div class="kpi-row" style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px">';
h+='<div class="card" style="text-align:center;padding:16px"><div style="color:#94a3b8;font-size:.75em;text-transform:uppercase;margin-bottom:6px">Pencapaian Kumulatif</div><div style="font-size:1.8em;font-weight:bold;color:'+sk.tx+'">'+fmtPct(KUMULATIF.pct)+'</div><div style="color:#64748b;font-size:.7em;margin-top:4px">s.d. Feb 2026</div></div>';
h+='<div class="card" style="text-align:center;padding:16px"><div style="color:#94a3b8;font-size:.75em;text-transform:uppercase;margin-bottom:6px">Realisasi kWh P2TL</div><div style="font-size:1.5em;font-weight:bold;background:linear-gradient(135deg,#60a5fa,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent">'+fmt(KUMULATIF.realisasi)+'</div><div style="color:#64748b;font-size:.7em;margin-top:4px">dari target '+fmt(KUMULATIF.target)+'</div></div>';
h+='<div class="card" style="text-align:center;padding:16px"><div style="color:#94a3b8;font-size:.75em;text-transform:uppercase;margin-bottom:6px">Gap kWh</div><div style="font-size:1.5em;font-weight:bold;color:'+gc+'">'+fmt(KUMULATIF.gap)+'</div><div style="color:#64748b;font-size:.7em;margin-top:4px">selisih target vs realisasi</div></div>';
h+='<div class="card" style="text-align:center;padding:16px"><div style="color:#94a3b8;font-size:.75em;text-transform:uppercase;margin-bottom:6px">Progress Tahunan</div><div style="font-size:1.5em;font-weight:bold;color:#fbbf24">'+prog.toFixed(1).replace(".",",")+'%</div><div style="color:#64748b;font-size:.7em;margin-top:4px">dari target '+fmt(TARGET_TAHUN.total)+' kWh</div></div></div>';
var ts='background:linear-gradient(135deg,#1e3a6e,#1a2d5e);color:#e2e8f0;padding:10px 8px;text-align:right;font-weight:600;font-size:.8em;text-transform:uppercase';
var fs='padding:10px 8px;text-align:right;color:#f8fafc;font-weight:700;background:linear-gradient(135deg,rgba(59,130,246,.15),rgba(139,92,246,.15));border-top:2px solid #3b82f6';
h+='<div class="card" style="padding:20px;margin-bottom:16px"><h4 style="color:#f8fafc;font-size:1em;margin:0 0 16px;display:flex;align-items:center;gap:8px">\u{1F4CB} Realisasi P2TL Kumulatif per ULP <span style="background:linear-gradient(135deg,#3b82f6,#8b5cf6);padding:2px 10px;border-radius:12px;font-size:.7em;color:#fff">s.d. Feb 2026</span></h4><div style="overflow-x:auto;border-radius:8px;border:1px solid #1e3054"><table style="width:100%;border-collapse:collapse;font-size:.8em"><thead><tr><th style="'+ts+';text-align:left">ULP</th><th style="'+ts+'">Target</th><th style="'+ts+'">Realisasi</th><th style="'+ts+'">Gap</th><th style="'+ts+'">Pencapaian</th><th style="'+ts+';text-align:center">Status</th></tr></thead><tbody>';
KUMULATIF.ulp.forEach(function(u){var s=getSC(u.pct);var b="border-bottom:1px solid rgba(30,48,84,.5)";h+='<tr><td style="padding:8px;color:#e2e8f0;font-weight:600;'+b+'">'+u.nama+'</td><td style="padding:8px;text-align:right;color:#cbd5e1;'+b+'">'+fmt(u.target)+'</td><td style="padding:8px;text-align:right;color:#f8fafc;font-weight:600;'+b+'">'+fmt(u.realisasi)+'</td><td style="padding:8px;text-align:right;color:'+gc+';'+b+'">'+fmt(u.gap)+'</td><td style="padding:8px;text-align:right;color:'+s.tx+';font-weight:600;'+b+'">'+fmtPct(u.pct)+'</td><td style="padding:8px;text-align:center;'+b+'">'+badge(u.pct)+'</td></tr>';});
h+='</tbody><tfoot><tr><td style="'+fs+';text-align:left">UP3 INDRAMAYU</td><td style="'+fs+'">'+fmt(KUMULATIF.target)+'</td><td style="'+fs+'">'+fmt(KUMULATIF.realisasi)+'</td><td style="'+fs+';color:'+gc+'">'+fmt(KUMULATIF.gap)+'</td><td style="'+fs+';color:'+sk.tx+'">'+fmtPct(KUMULATIF.pct)+'</td><td style="'+fs+';text-align:center">'+badge(KUMULATIF.pct)+'</td></tr></tfoot></table></div></div>';
var mx=0;BULAN_DATA.forEach(function(b){if(b.target>mx)mx=b.target;if(b.realisasi>mx)mx=b.realisasi;});
var tb='';BULAN_DATA.forEach(function(b,i){var hT=Math.max((b.target/mx)*140,4);var hR=Math.max((b.realisasi/mx)*140,4);var rc=b.pct>=100?"#10b981":b.pct>=90?"#3b82f6":"#f59e0b";tb+='<div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:4px"><div style="display:flex;align-items:flex-end;gap:4px;height:160px"><div style="width:28px;height:'+hT+'px;background:rgba(100,116,139,.3);border-radius:3px 3px 0 0;border:1px solid rgba(100,116,139,.4)"></div><div style="width:28px;height:'+hR+'px;background:'+rc+';border-radius:3px 3px 0 0;opacity:.85"></div></div><div style="font-size:.8em;color:#94a3b8;font-weight:600">'+BULAN_LABELS[i]+'</div><div style="font-size:.65em;color:'+rc+';font-weight:600">'+fmtPct(b.pct)+'</div></div>';});
var uc=["#3b82f6","#8b5cf6","#06b6d4","#f59e0b"];var ub='';
KUMULATIF.ulp.forEach(function(u,i){var bw=Math.min((u.realisasi/u.target*100),100).toFixed(0);ub+='<div style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><div style="width:80px;font-size:.75em;color:#94a3b8;text-align:right">'+u.kode+'</div><div style="flex:1;height:24px;background:rgba(30,48,84,.3);border-radius:6px;overflow:hidden"><div style="height:100%;width:'+bw+'%;background:'+uc[i]+';display:flex;align-items:center;justify-content:center;font-size:.65em;color:#fff;font-weight:600">'+fmtPct(u.pct)+'</div></div><div style="width:70px;font-size:.75em;color:#e2e8f0;font-weight:600;text-align:right">'+fmt(u.realisasi)+'</div></div>';});
var best=KUMULATIF.ulp.slice().sort(function(a,b){return b.pct-a.pct;})[0];
var worst=KUMULATIF.ulp.slice().sort(function(a,b){return a.pct-b.pct;})[0];
h+='<div class="chart-row" style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px"><div class="card" style="padding:20px"><h4 style="color:#f8fafc;margin:0 0 16px;font-size:1em">\u{1F4C8} Trend Realisasi P2TL Bulanan</h4><div style="display:flex;gap:8px;margin-bottom:12px"><div style="display:flex;align-items:center;gap:4px;font-size:.7em;color:#94a3b8"><div style="width:12px;height:12px;background:rgba(100,116,139,.3);border:1px solid rgba(100,116,139,.4);border-radius:2px"></div>Target</div><div style="display:flex;align-items:center;gap:4px;font-size:.7em;color:#94a3b8"><div style="width:12px;height:12px;background:#3b82f6;border-radius:2px"></div>Realisasi</div></div><div style="display:flex;align-items:flex-end;justify-content:center;gap:24px;padding:10px 0">'+tb+'</div></div>';
h+='<div class="card" style="padding:20px"><h4 style="color:#f8fafc;margin:0 0 16px;font-size:1em">\u{1F3AF} Pencapaian per ULP (Kumulatif)</h4><div style="padding:8px 0">'+ub+'</div><div style="margin-top:12px;padding:10px;background:rgba(59,130,246,.08);border-radius:8px;border-left:3px solid #3b82f6"><div style="font-size:.75em;color:#60a5fa;font-weight:600">\u{1F4CC} Insight</div><div style="font-size:.72em;color:#94a3b8;margin-top:4px">'+best.nama+' memiliki pencapaian tertinggi ('+fmtPct(best.pct)+'). '+worst.nama+' perlu perhatian ('+fmtPct(worst.pct)+').</div></div></div></div>';
// Detail table
h+='<div class="card" style="padding:20px;margin-bottom:16px"><h4 style="color:#f8fafc;font-size:1em;margin:0 0 16px">\u{1F4CA} Detail Realisasi P2TL Bulanan per ULP</h4><div style="overflow-x:auto;border-radius:8px;border:1px solid #1e3054"><table style="width:100%;border-collapse:collapse;font-size:.78em"><thead><tr><th style="'+ts+';text-align:left" rowspan="2">ULP</th>';
BULAN_LABELS.forEach(function(bl){h+='<th style="'+ts+';text-align:center" colspan="3">'+bl.toUpperCase()+'</th>';});
h+='</tr><tr>';BULAN_LABELS.forEach(function(){h+='<th style="'+ts+';font-size:.75em">Target</th><th style="'+ts+';font-size:.75em">Realisasi</th><th style="'+ts+';font-size:.75em">%</th>';});
h+='</tr></thead><tbody>';
for(var u=0;u<4;u++){var bs="border-bottom:1px solid rgba(30,48,84,.5)";h+='<tr><td style="padding:7px 8px;color:#e2e8f0;font-weight:600;'+bs+'">'+KUMULATIF.ulp[u].nama+'</td>';BULAN_DATA.forEach(function(b){var d=b.ulp[u];var pc=getSC(d.pct).tx;h+='<td style="padding:7px 8px;text-align:right;color:#cbd5e1;'+bs+'">'+fmt(d.target)+'</td><td style="padding:7px 8px;text-align:right;color:#f8fafc;font-weight:500;'+bs+'">'+fmt(d.realisasi)+'</td><td style="padding:7px 8px;text-align:right;color:'+pc+';font-weight:600;'+bs+'">'+fmtPct(d.pct)+'</td>';});h+='</tr>';}
h+='</tbody><tfoot><tr><td style="'+fs+';text-align:left">UP3 INDRAMAYU</td>';
BULAN_DATA.forEach(function(b){var pc=getSC(b.pct).tx;h+='<td style="'+fs+'">'+fmt(b.target)+'</td><td style="'+fs+'">'+fmt(b.realisasi)+'</td><td style="'+fs+';color:'+pc+'">'+fmtPct(b.pct)+'</td>';});
h+='</tr></tfoot></table></div></div>';
// Analisis
var fst=BULANAN.feb.pct>=100?"melampaui":"belum mencapai";
h+='<div class="card" style="padding:20px;margin-bottom:16px;border-left:3px solid #8b5cf6"><h4 style="color:#f8fafc;font-size:1em;margin:0 0 16px">\u{1F4A1} Analisis Kinerja P2TL</h4><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">';
h+='<div style="padding:12px;background:rgba(16,185,129,.06);border-radius:8px"><div style="color:#34d399;font-weight:600;font-size:.82em;margin-bottom:6px">\u{1F7E2} Pencapaian Februari</div><div style="color:#94a3b8;font-size:.75em">Realisasi Februari '+fst+' target ('+fmtPct(BULANAN.feb.pct)+'). Seluruh ULP >100%.</div></div>';
h+='<div style="padding:12px;background:rgba(245,158,11,.06);border-radius:8px"><div style="color:#fbbf24;font-weight:600;font-size:.82em;margin-bottom:6px">\u{1F7E1} Gap Kumulatif</div><div style="color:#94a3b8;font-size:.75em">Gap kumulatif '+fmt(Math.abs(KUMULATIF.gap))+' kWh. Defisit terbesar dari Januari (93,62%).</div></div>';
h+='<div style="padding:12px;background:rgba(59,130,246,.06);border-radius:8px"><div style="color:#60a5fa;font-weight:600;font-size:.82em;margin-bottom:6px">\u{1F535} Progress Tahunan</div><div style="color:#94a3b8;font-size:.75em">Progress '+prog.toFixed(1).replace(".",",")+'% dari target tahunan '+fmt(TARGET_TAHUN.total)+' kWh.</div></div>';
h+='<div style="padding:12px;background:rgba(139,92,246,.06);border-radius:8px"><div style="color:#a78bfa;font-weight:600;font-size:.82em;margin-bottom:6px">\u{1F4CD} Fokus Area</div><div style="color:#94a3b8;font-size:.75em">'+worst.nama+' ('+worst.kode+') pencapaian terendah '+fmtPct(worst.pct)+'. Intensifkan P2TL.</div></div>';
h+='</div></div>';
h+='<div style="text-align:center;padding:8px;color:#475569;font-size:.7em">Sumber: KINERJA TE 2026 \u2014 Realisasi Semester I | UP3 Indramayu</div>';
sec.innerHTML=h;
if(rk){ct.insertBefore(sec,rk);}else{ct.appendChild(sec);}
}
var obs=new MutationObserver(function(ml){ml.forEach(function(m){m.addedNodes.forEach(function(n){if(n.nodeType===1&&(n.textContent||"").indexOf("Pengendalian Susut Distribusi")!==-1)setTimeout(renderP2TL,300);});});});
obs.observe(document.body,{childList:true,subtree:true});
setTimeout(renderP2TL,1500);
setInterval(function(){var ct=document.getElementById("ct");if(ct){var ok=false;for(var i=0;i<ct.children.length;i++){if((ct.children[i].textContent||"").indexOf("Pengendalian Susut Distribusi")!==-1){ok=true;break;}}if(ok&&!document.getElementById("p2tl-kinerja-section"))renderP2TL();}},2000);
})();
